backend:
  name: github
  repo: bolioliagustin/grupo-scout-7mo   # ← CAMBIAR
  branch: main
  # (no hace falta auth_endpoint si usás el OAuth de Netlify)

media_folder: "assets/uploads"
public_folder: "/assets/uploads"
publish_mode: editorial_workflow
locale: "es"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "content/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Autor", name: "author", widget: "string", required: false }
      - { label: "Resumen", name: "excerpt", widget: "text", required: false }
      - { label: "Imagen de portada", name: "cover", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Autor", name: "author", widget: "string", required: false }
      - { label: "Resumen", name: "excerpt", widget: "text", required: false }
      - { label: "Imagen de portada", name: "cover", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
